<?php

namespace App\Domain\Models;

use App\UserService;
use Illuminate\Support\Arr;

class Slots
{

    // --------------- Instagram -------------------

    const INSTAGRAM_LIKES_LK_VKSERFING = 'INSTAGRAM_LIKES_LK_VKSERFING';
    const INSTAGRAM_LIKES_LK_EVERVE = 'INSTAGRAM_LIKES_LK_EVERVE';
    const INSTAGRAM_LIKES_LK_SOCGRESS = 'INSTAGRAM_LIKES_LK_SOCGRESS';
    const INSTAGRAM_LIKES_LK_NAKRUTKA = 'INSTAGRAM_LIKES_LK_NAKRUTKA';
    const INSTAGRAM_LIKES_LK_NAKRUTKA_2 = 'INSTAGRAM_LIKES_LK_NAKRUTKA_2';
    const INSTAGRAM_LIKES_LK_NAKRUTKA_3 = 'INSTAGRAM_LIKES_LK_NAKRUTKA_3';
    const INSTAGRAM_LIKES_LK_NAKRUTKA_4 = 'INSTAGRAM_LIKES_LK_NAKRUTKA_4';
    const INSTAGRAM_LIKES_LK_NAKRUTKA_5 = 'INSTAGRAM_LIKES_LK_NAKRUTKA_5';
    const INSTAGRAM_LIKES_LK_VTOPE = 'INSTAGRAM_LIKES_LK_VTOPE';

    const INSTAGRAM_LIKES_MAIN_VKSERFING = 'INSTAGRAM_LIKES_MAIN_VKSERFING';
    const INSTAGRAM_LIKES_MAIN_EVERVE = 'INSTAGRAM_LIKES_MAIN_EVERVE';
    const INSTAGRAM_LIKES_MAIN_SOCGRESS = 'INSTAGRAM_LIKES_MAIN_SOCGRESS';
    const INSTAGRAM_LIKES_MAIN_NAKRUTKA = 'INSTAGRAM_LIKES_MAIN_NAKRUTKA';
    const INSTAGRAM_LIKES_MAIN_NAKRUTKA_2 = 'INSTAGRAM_LIKES_MAIN_NAKRUTKA_2';
    const INSTAGRAM_LIKES_MAIN_NAKRUTKA_3 = 'INSTAGRAM_LIKES_MAIN_NAKRUTKA_3';
    const INSTAGRAM_LIKES_MAIN_NAKRUTKA_4 = 'INSTAGRAM_LIKES_MAIN_NAKRUTKA_4';
    const INSTAGRAM_LIKES_MAIN_NAKRUTKA_5 = 'INSTAGRAM_LIKES_MAIN_NAKRUTKA_5';

    const INSTAGRAM_SUBS_LK_EVERVE = 'INSTAGRAM_SUBS_LK_EVERVE';
    const INSTAGRAM_SUBS_LK_VKSERFING = 'INSTAGRAM_SUBS_LK_VKSERFING';
    const INSTAGRAM_SUBS_LK_NAKRUTKA = 'INSTAGRAM_SUBS_LK_NAKRUTKA';
    const INSTAGRAM_SUBS_LK_SOCGRESS = 'INSTAGRAM_SUBS_LK_SOCGRESS';
    const INSTAGRAM_SUBS_LK_NAKRUTKA_2 = 'INSTAGRAM_SUBS_LK_NAKRUTKA_2';

    const INSTAGRAM_SUBS_MAIN_EVERVE = 'INSTAGRAM_SUBS_MAIN_EVERVE';
    const INSTAGRAM_SUBS_MAIN_VKSERFING = 'INSTAGRAM_SUBS_MAIN_VKSERFING';
    const INSTAGRAM_SUBS_MAIN_NAKRUTKA = 'INSTAGRAM_SUBS_MAIN_NAKRUTKA';
    const INSTAGRAM_SUBS_MAIN_SOCGRESS = 'INSTAGRAM_SUBS_MAIN_SOCGRESS';

    const INSTAGRAM_AUTO_LIKES_LK_NAKRUTKA_AUTO = 'INSTAGRAM_AUTO_LIKES_LK_NAKRUTKA_AUTO';
    const INSTAGRAM_AUTO_VIEWS_LK_NAKRUTKA_AUTO = 'INSTAGRAM_AUTO_VIEWS_LK_NAKRUTKA_AUTO';

    const INSTAGRAM_AUTO_LIKES_MAIN_NAKRUTKA_AUTO = 'INSTAGRAM_AUTO_LIKES_MAIN_NAKRUTKA_AUTO';
    const INSTAGRAM_AUTO_VIEWS_MAIN_NAKRUTKA_AUTO = 'INSTAGRAM_AUTO_VIEWS_MAIN_NAKRUTKA_AUTO';

    const INSTAGRAM_COMMENTS_CUSTOM_LK_VKSERFING = 'INSTAGRAM_COMMENTS_CUSTOM_LK_VKSERFING';
    const INSTAGRAM_COMMENTS_POSITIVE_LK_VKSERFING = 'INSTAGRAM_COMMENTS_POSITIVE_LK_VKSERFING';
    const INSTAGRAM_MULTI_COMMENTS_CUSTOM_LK_VKSERFING = 'INSTAGRAM_MULTI_COMMENTS_CUSTOM_LK_VKSERFING';
    const INSTAGRAM_MULTI_COMMENTS_POSITIVE_LK_VKSERFING = 'INSTAGRAM_MULTI_COMMENTS_POSITIVE_LK_VKSERFING';

    const INSTAGRAM_MULTI_LIKES_LK_VKSERFING = 'INSTAGRAM_MULTI_LIKES_LK_VKSERFING';
    const INSTAGRAM_MULTI_LIKES_LK_EVERVE = 'INSTAGRAM_MULTI_LIKES_LK_EVERVE';
    const INSTAGRAM_MULTI_LIKES_LK_SOCGRESS = 'INSTAGRAM_MULTI_LIKES_LK_SOCGRESS';
    const INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA = 'INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA';
    const INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_2 = 'INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_2';
    const INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_3 = 'INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_3';
    const INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_4 = 'INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_4';
    const INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_5 = 'INSTAGRAM_MULTI_LIKES_LK_NAKRUTKA_5';

    const INSTAGRAM_MULTI_LIKES_MAIN_VKSERFING = 'INSTAGRAM_MULTI_LIKES_MAIN_VKSERFING';
    const INSTAGRAM_MULTI_LIKES_MAIN_EVERVE = 'INSTAGRAM_MULTI_LIKES_MAIN_EVERVE';
    const INSTAGRAM_MULTI_LIKES_MAIN_SOCGRESS = 'INSTAGRAM_MULTI_LIKES_MAIN_SOCGRESS';
    const INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA = 'INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA';
    const INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_2 = 'INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_2';
    const INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_3 = 'INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_3';
    const INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_4 = 'INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_4';
    const INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_5 = 'INSTAGRAM_MULTI_LIKES_MAIN_NAKRUTKA_5';

    const INSTAGRAM_LIVE_LIKES_LK_NAKRUTKA = 'INSTAGRAM_LIVE_LIKES_LK_NAKRUTKA';

    const INSTAGRAM_VIEWS_IGTV_LK_NAKRUTKA = 'INSTAGRAM_VIEWS_IGTV_LK_NAKRUTKA';

    const INSTAGRAM_VIEWS_SHOWS_IMPRESSIONS_LK_NAKRUTKA = 'INSTAGRAM_VIEWS_SHOWS_IMPRESSIONS_LK_NAKRUTKA';

    const INSTAGRAM_VIEWS_STORY_LK_SOCGRESS = 'INSTAGRAM_VIEWS_STORY_LK_SOCGRESS';
    const INSTAGRAM_VIEWS_STORY_LK_NAKRUTKA = 'INSTAGRAM_VIEWS_STORY_LK_NAKRUTKA';

    const INSTAGRAM_VIEWS_STORY_MAIN_SOCGRESS = 'INSTAGRAM_VIEWS_STORY_MAIN_SOCGRESS';
    const INSTAGRAM_VIEWS_STORY_MAIN_NAKRUTKA = 'INSTAGRAM_VIEWS_STORY_MAIN_NAKRUTKA';

    const INSTAGRAM_VIEWS_VIDEO_LK_NAKRUTKA = 'INSTAGRAM_VIEWS_VIDEO_LK_NAKRUTKA';

    const INSTAGRAM_VIEWS_VIDEO_MAIN_NAKRUTKA = 'INSTAGRAM_VIEWS_VIDEO_MAIN_NAKRUTKA';

    const INSTAGRAM_LIVE_VIEWERS_LK_NAKRUTKA = 'INSTAGRAM_LIVE_VIEWERS_LK_NAKRUTKA';


    // ------------------ TikTok ----------------------

    const TIKTOK_AUTO_LIKES_LK_VKSERFING_AUTO = 'TIKTOK_AUTO_LIKES_LK_VKSERFING_AUTO';
    const TIKTOK_AUTO_VIEWS_LK_VKSERFING_AUTO = 'TIKTOK_AUTO_VIEWS_LK_VKSERFING_AUTO';

    const TIKTOK_AUTO_LIKES_MAIN_VKSERFING_AUTO = 'TIKTOK_AUTO_LIKES_MAIN_VKSERFING_AUTO';
    const TIKTOK_AUTO_VIEWS_MAIN_VKSERFING_AUTO = 'TIKTOK_AUTO_VIEWS_MAIN_VKSERFING_AUTO';

    const TIKTOK_COMMENTS_CUSTOM_LK_VKSERFING = 'TIKTOK_COMMENTS_CUSTOM_LK_VKSERFING';
    const TIKTOK_COMMENTS_POSITIVE_LK_VKSERFING = 'TIKTOK_COMMENTS_POSITIVE_LK_VKSERFING';

    const TIKTOK_LIKES_LK_VTOPE = 'TIKTOK_LIKES_LK_VTOPE';
    const TIKTOK_LIKES_LK_NAKRUTKA = 'TIKTOK_LIKES_LK_NAKRUTKA';
    const TIKTOK_LIKES_LK_SOCGRESS = 'TIKTOK_LIKES_LK_SOCGRESS';
    const TIKTOK_LIKES_LK_VKSERFING = 'TIKTOK_LIKES_LK_VKSERFING';
    const TIKTOK_LIKES_LK_EVERVE = 'TIKTOK_LIKES_LK_EVERVE';

    const TIKTOK_LIKES_MAIN_VTOPE = 'TIKTOK_LIKES_MAIN_VTOPE';
    const TIKTOK_LIKES_MAIN_NAKRUTKA = 'TIKTOK_LIKES_MAIN_NAKRUTKA';
    const TIKTOK_LIKES_MAIN_SOCGRESS = 'TIKTOK_LIKES_MAIN_SOCGRESS';
    const TIKTOK_LIKES_MAIN_VKSERFING = 'TIKTOK_LIKES_MAIN_VKSERFING';
    const TIKTOK_LIKES_MAIN_EVERVE = 'TIKTOK_LIKES_MAIN_EVERVE';

    const TIKTOK_REPOSTS_LK_VKSERFING = 'TIKTOK_REPOSTS_LK_VKSERFING';

    const TIKTOK_REPOSTS_MAIN_VKSERFING = 'TIKTOK_REPOSTS_MAIN_VKSERFING';

    const TIKTOK_SUBS_LK_VTOPE = 'TIKTOK_SUBS_LK_VTOPE';
    const TIKTOK_SUBS_LK_SOCGRESS = 'TIKTOK_SUBS_LK_SOCGRESS';
    const TIKTOK_SUBS_LK_VKSERFING = 'TIKTOK_SUBS_LK_VKSERFING';
    const TIKTOK_SUBS_LK_NAKRUTKA = 'TIKTOK_SUBS_LK_NAKRUTKA';

    const TIKTOK_SUBS_MAIN_VTOPE = 'TIKTOK_SUBS_MAIN_VTOPE';
    const TIKTOK_SUBS_MAIN_SOCGRESS = 'TIKTOK_SUBS_MAIN_SOCGRESS';
    const TIKTOK_SUBS_MAIN_VKSERFING = 'TIKTOK_SUBS_MAIN_VKSERFING';
    const TIKTOK_SUBS_MAIN_NAKRUTKA = 'TIKTOK_SUBS_MAIN_NAKRUTKA';

    const TIKTOK_VIEWS_LK_NAKRUTKA = 'TIKTOK_VIEWS_LK_NAKRUTKA';
    const TIKTOK_VIEWS_LK_NAKRUTKA_2 = 'TIKTOK_VIEWS_LK_NAKRUTKA_2';
    const TIKTOK_VIEWS_LK_SOCGRESS = 'TIKTOK_VIEWS_LK_SOCGRESS';

    const TIKTOK_VIEWS_MAIN_NAKRUTKA = 'TIKTOK_VIEWS_MAIN_NAKRUTKA';
    const TIKTOK_VIEWS_MAIN_NAKRUTKA_2 = 'TIKTOK_VIEWS_MAIN_NAKRUTKA_2';
    const TIKTOK_VIEWS_MAIN_SOCGRESS = 'TIKTOK_VIEWS_MAIN_SOCGRESS';


    // ----------------- VK -----------------

    const VK_AUTO_LIKES_LK_VKSERFING = 'VK_AUTO_LIKES_LK_VKSERFING';
    const VK_AUTO_LIKES_LK_VKSERFING_AUTO = 'VK_AUTO_LIKES_LK_VKSERFING_AUTO';

    const VK_AUTO_LIKES_MAIN_VKSERFING = 'VK_AUTO_LIKES_MAIN_VKSERFING';
    const VK_AUTO_LIKES_MAIN_VKSERFING_AUTO = 'VK_AUTO_LIKES_MAIN_VKSERFING_AUTO';

    const VK_COMMENTS_LK_VKSERFING = 'VK_COMMENTS_LK_VKSERFING';
    const VK_COMMENTS_MAIN_VKSERFING = 'VK_COMMENTS_MAIN_VKSERFING';

    const VK_FRIENDS_LK_VKSERFING = 'VK_FRIENDS_LK_VKSERFING';

    const VK_FRIENDS_MAIN_NAKRUTKA = 'VK_FRIENDS_MAIN_NAKRUTKA';
    const VK_FRIENDS_MAIN_NAKRUTKA_2 = 'VK_FRIENDS_MAIN_NAKRUTKA_2';
    const VK_FRIENDS_MAIN_VKSERFING = 'VK_FRIENDS_MAIN_VKSERFING';

    const VK_LIKES_LK_VKSERFING = 'VK_LIKES_LK_VKSERFING';
    const VK_LIKES_MAIN_VKSERFING = 'VK_LIKES_MAIN_VKSERFING';

    const VK_REPOSTS_LK_EVERVE = 'VK_REPOSTS_LK_EVERVE';
    const VK_REPOSTS_MAIN_EVERVE = 'VK_REPOSTS_MAIN_EVERVE';

    const VK_SUBS_LK_NAKRUTKA = 'VK_SUBS_LK_NAKRUTKA';
    const VK_SUBS_LK_VKSERFING = 'VK_SUBS_LK_VKSERFING';

    const VK_SUBS_MAIN_NAKRUTKA = 'VK_SUBS_MAIN_NAKRUTKA';
    const VK_SUBS_MAIN_NAKRUTKA_2 = 'VK_SUBS_MAIN_NAKRUTKA_2';
    const VK_SUBS_MAIN_VKSERFING = 'VK_SUBS_MAIN_VKSERFING';


    // ----------------- YouTube -----------------

    const YOUTUBE_DISLIKES_LK_NAKRUTKA = 'YOUTUBE_DISLIKES_LK_NAKRUTKA';
    const YOUTUBE_DISLIKES_MAIN_NAKRUTKA = 'YOUTUBE_DISLIKES_MAIN_NAKRUTKA';

    const YOUTUBE_LIKES_LK_NAKRUTKA = 'YOUTUBE_LIKES_LK_NAKRUTKA';
    const YOUTUBE_LIKES_MAIN_NAKRUTKA = 'YOUTUBE_LIKES_MAIN_NAKRUTKA';

    const YOUTUBE_SUBS_LK_NAKRUTKA = 'YOUTUBE_SUBS_LK_NAKRUTKA';
    const YOUTUBE_SUBS_MAIN_NAKRUTKA = 'YOUTUBE_SUBS_MAIN_NAKRUTKA';

    const YOUTUBE_VIEWS_LK_NAKRUTKA = 'YOUTUBE_VIEWS_LK_NAKRUTKA';
    const YOUTUBE_VIEWS_MAIN_NAKRUTKA = 'YOUTUBE_VIEWS_MAIN_NAKRUTKA';


    // ---------------- Test -------------------

    const FAKE_SERVICE_LK_FAKE_1 = 'FAKE_SERVICE_LK_FAKE_1';
    const FAKE_SERVICE_LK_FAKE_2 = 'FAKE_SERVICE_LK_FAKE_2';

    const IG_LIKES_TEST_LOCAL = 'IG_LIKES_TEST_LOCAL';

    public static function getSlotFromArray(string $name, array $slots): ?array
    {
        return collect($slots)->firstWhere('name', $name);
    }

    public static function getConfig(string $slotName): ?array
    {
        foreach(UserService::all() as $service)
        {
            $slot = self::getSlotFromArray($slotName, $service->config);
            if (! empty($slot)) {
                return $slot;
            }
        }

        return null;
    }

    public static function searchForSlotInService($slotName, $userService):int
    {
        foreach($userService->config as $index => $config) {
            if (Arr::get($config, 'name') === $slotName) {
                return $index;
            }
        }

        return -1;
    }

    // has bug ???
    public static function mergeSlotConfig(string $slotName, array $newConfig)
    {
        foreach(UserService::all() as $service) {
            $index = self::searchForSlotInService($slotName, $service);
            if ($index !== -1) {
                $slots = $service->config;
                $slots[$index] = array_merge($slots[$index], $newConfig);
                $service->config = $slots;
                $service->save();

                return true;
            }
        }
        return false;
    }

    public static function deepMergeSlotConfig($slotName, $key, $value)
    {
        $slot = self::getConfig($slotName);
        $slot[$key] = array_merge($slot[$key], $value);
        self::mergeSlotConfig($slotName, $slot);
    }

    public static function mergeSlotNetCost(string $slotName, array $netCost)
    {
        self::deepMergeSlotConfig($slotName, 'net_cost', $netCost);
    }

//    public static function getConfig(string $slotName): ?array
//    {
//        return self::_getConfig($slotName);
//
////        do we really need it?
////        return Cache::remember(
////            __METHOD__ . $slotName,
////            30,
////            fn() => self::_getConfig($slotName)
////        );
//    }
}
